### ISSUE TITLE
"Acces denied" for duplex communication on Windows

### ISSUE THREAD

**Issue by gggto** [Eolu/ipipe#11]
`ipipe` seems to use duplex named-pipes on Windows, however, trying to `write` and then `read` data results in a `PermissionDenied` error.

Minimal non-working example: [pipetest.zip](https://github.com/Eolu/ipipe/files/8155380/pipetest.zip).

Windows 10 (21H1), rustc 1.56.1 and 1.59, ipipe 0.11.2

**Comment by Eolu** [comment]
Thanks for the issue report, I'll look into this sometime this week

**Comment by Eolu** [comment]
So the latest version does fix this problem, and results in your example working on Windows. That said, it also reveals [another issue](https://github.com/Eolu/ipipe/issues/12). As long as that problem exists, the implementation provided in your example would have to be modified to look like this in order to function without errors and behave identically across Windows and Unix: 
```rust
use ipipe::Pipe;
use std::io::stdout;
use std::io::BufRead;
use std::io::BufReader;
use std::thread;

use std::io::Write;

fn print_line(buf_reader: &mut BufReader<Pipe>) 
{
    let mut buf = vec![];
    buf_reader.read_until(b'\n', &mut buf).unwrap();
    print!("{}", String::from_utf8(buf).unwrap());
    stdout().flush().unwrap();
}

fn client_server1(mut pipe: Pipe) 
{
    writeln!(pipe, "test1").unwrap();
    writeln!(pipe, "test2").unwrap();
    writeln!(pipe, "test3").unwrap();
    let mut buf_reader = BufReader::new(pipe);
    print_line(&mut buf_reader);
    print_line(&mut buf_reader);
    print_line(&mut buf_reader);
}

fn client_server2(pipe: Pipe) 
{
    let mut buf_reader = BufReader::new(pipe);
    print_line(&mut buf_reader);
    print_line(&mut buf_reader);
    print_line(&mut buf_reader);
    let mut pipe = buf_reader.into_inner();
    writeln!(pipe, "test4").unwrap();
    writeln!(pipe, "test5").unwrap();
    writeln!(pipe, "test6").unwrap();
}

fn main() 
{
    let pipe = Pipe::with_name("test").unwrap();
    let pipe_clone = pipe.clone();
    let t1 = thread::spawn(|| client_server1(pipe));
    let t2 = thread::spawn(|| client_server2(pipe_clone));
    t1.join().unwrap();
    t2.join().unwrap();
}

```

I've updated the README to clarify this, but obviously it would be better if the API were able to completely disallow invalid use. I'm investigating ways to modify the API or the underlying implementation to hopefully either make this impossible at compile time, or handled implicitly at runtime.

**Comment by gggto** [comment]
Well, I used threads in that example for the sake of simplicity; I'm not sure pipes are much more useful than what `crossbeam::channel` or even `std::mpsc::channel` provides in that exact case. Since I actually use differents binaries for client and server in the real app, I can't really modify my code as you suggest.

Anyway, my use case currently only requires Windows support, so I'll test and report to you if this issue is fixed on my side tomorrow.

Thank you!

**Comment by gggto** [comment]
As far as I can tell, the issue is fixed on my side.
